# Generated by Django 5.0 on 2023-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('machine', models.CharField(max_length=100)),
                ('machine_id', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pictures', models.ImageField(upload_to='machine_pics/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('insta', models.CharField(blank=True, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
